name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9, '3.10', 3.11]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        # Install jq
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          sudo apt-get update
          sudo apt-get install -y jq
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          brew install jq
        fi
        
        # Install Python dependencies
        python -m pip install --upgrade pip
        pip install black ruff pytest

    - name: Lint with ruff
      run: |
        ruff check src/

    - name: Check code formatting
      run: |
        black --check src/

    - name: Check shell scripts
      run: |
        # Install shellcheck
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          sudo apt-get install -y shellcheck
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          brew install shellcheck
        fi
        
        # Check shell scripts
        find src scripts -name "*.sh" -exec shellcheck {} \;

    - name: Test Python syntax
      run: |
        python -m py_compile src/*.py

    - name: Run tests
      run: |
        ./tests/test.sh

  package:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v3

    - name: Create package
      run: |
        make package

    - name: Upload package
      uses: actions/upload-artifact@v3
      with:
        name: codechats-manager-package
        path: dist/