name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq shellcheck

    - name: Check syntax
      run: |
        bash -n src/codechats-main.sh
        python3 -m py_compile src/codechats-cache.py
        # Only check for critical errors, ignore style warnings
        shellcheck -S error src/codechats-main.sh

    - name: Python quality
      run: |
        pip install ruff black
        ruff check src/
        black --check src/

    - name: Test basic functionality
      run: |
        echo "✅ All basic checks passed"
        echo "🎉 CodeChats Manager is ready!"